// FILE: QRScannerPairingValidator.swift
// Purpose: Classifies scanned QR payloads so the pairing flow can block outdated Mac bridges before reconnecting.
// Layer: View support
// Exports: validatePairingQRCode
// Depends on: Foundation, CodexPairingQRPayload, CodexBridgeUpdatePrompt

import Foundation

enum QRScannerPairingValidationResult {
    case success(CodexPairingQRPayload)
    case scanError(String)
    case bridgeUpdateRequired(CodexBridgeUpdatePrompt)
}

private let qrScannerBridgeUpdateCommand = AppEnvironment.sourceBridgeUpdateCommand

// Distinguishes a usable pairing QR from stale bridge payloads and generic camera mis-scans.
func validatePairingQRCode(_ code: String, now: Date = Date()) -> QRScannerPairingValidationResult {
    guard let data = code.data(using: .utf8) else {
        return .scanError("QR code contains invalid text encoding.")
    }

    let decoder = JSONDecoder()
    if let payload = try? decoder.decode(CodexPairingQRPayload.self, from: data) {
        guard payload.v == codexPairingQRVersion else {
            return .bridgeUpdateRequired(
                makeScannerBridgeUpdatePrompt(
                    message: "This QR code was generated by a different iCodex bridge build. Update your local bridge checkout on your Mac before scanning a new QR code."
                )
            )
        }

        guard !payload.relay.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            return .scanError("QR code is missing the relay URL. Re-generate the code from the bridge.")
        }

        guard !payload.sessionId.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            return .scanError("QR code is missing the session ID. Re-generate the code from the bridge.")
        }

        let expiryDate = Date(timeIntervalSince1970: TimeInterval(payload.expiresAt) / 1000)
        guard expiryDate.addingTimeInterval(codexSecureClockSkewToleranceSeconds) >= now else {
            return .scanError("This pairing QR code has expired. Generate a new one from the Mac bridge.")
        }

        return .success(payload)
    }

    if looksLikeICodexPairingPayload(data) {
        return .bridgeUpdateRequired(
            makeScannerBridgeUpdatePrompt(
                message: "This QR code looks like it came from an older iCodex bridge. Update your local bridge checkout on your Mac before scanning a new QR code."
            )
        )
    }

    return .scanError("Not a valid secure pairing code. Make sure you're scanning a QR from the latest iCodex bridge.")
}

private func looksLikeICodexPairingPayload(_ data: Data) -> Bool {
    guard let jsonObject = try? JSONSerialization.jsonObject(with: data),
          let object = jsonObject as? [String: Any] else {
        return false
    }

    let pairingKeys: Set<String> = [
        "relay",
        "sessionId",
        "macDeviceId",
        "macIdentityPublicKey",
        "expiresAt",
        "v",
    ]
    return !pairingKeys.isDisjoint(with: object.keys)
}

private func makeScannerBridgeUpdatePrompt(message: String) -> CodexBridgeUpdatePrompt {
    CodexBridgeUpdatePrompt(
        title: "Update iCodex on your Mac before scanning",
        message: message,
        command: qrScannerBridgeUpdateCommand
    )
}
